name: "Cron Build Debug"

on:
  schedule:
    - cron: '*/20 * * * *'
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11 ]
        graal: [ 19.3.1, 20.0.0 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Pull Quarkus Native Builder Image ${{ matrix.graal }}-java${{ matrix.java }}
        run: docker pull quay.io/quarkus/ubi-quarkus-native-image:${{ matrix.graal }}-java${{ matrix.java }}

      - name: Initial Build
        run: mvn -B clean package -DskipTests

      - name: Build - JVM
        run: for i in $(seq 1 50); do PN_TRACE_FRM=true mvn -B clean verify -Dquarkus.log.category.\"org.apache.qpid.jms\".level=trace || ! break; done
